name: Fetch and Update Stream M3U

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        working-directory: scraper
        run: npm install

      - name: Run Fetch Script
        working-directory: scraper
        env:
          HOTSTAR_M3U: ${{ secrets.HOTSTAR_M3U }}
          ZEE5_M3U: ${{ secrets.ZEE5_M3U }}
          SONYLIV_M3U: ${{ secrets.SONYLIV_M3U }}
          SUNXT_M3U: ${{ secrets.SUNXT_M3U }}
          JSTAR_LIVE_EVENTS: ${{ secrets.JSTAR_LIVE_EVENTS }}
          WORLDWIDE_EVENTS: ${{ secrets.WORLDWIDE_EVENTS }}
          WILLOW_LIVE_EVENTS: ${{ secrets.WILLOW_LIVE_EVENTS }}
        run: npm start

      - name: Commit and Push stream.m3u
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          git pull --rebase origin main

          cp scraper/stream.m3u stream.m3u
          git add stream.m3u

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "📥 updated stream.m3u from remote source"
            git push origin main
          fi
